# File generated with docstub

import numba
import numpy as np
import scipy
import xarray as xr
from _typeshed import Incomplete
from scipy.fftpack import next_fast_len
from xarray_einstats import stats
from xarray_einstats.einops import rearrange

__all__ = ["rhat", "ess"]

def _backtransform_ranks(da: xr.DataArray, c: float = ...) -> xr.DataArray: ...
def _z_scale(da: xr.DataArray, **kwargs: Incomplete) -> xr.DataArray: ...
def _split_chains(da: Incomplete, **kwargs: Incomplete) -> None: ...
def _z_fold(da: Incomplete, **kwargs: Incomplete) -> None: ...
def _rhat(da: Incomplete) -> None: ...
def _rhat_rank(da: Incomplete, **kwargs: Incomplete) -> None: ...
def rhat(
    ds: Incomplete, group: Incomplete = ..., method: Incomplete = ..., **kwargs: Incomplete
) -> None: ...
def rfft(
    da: Incomplete,
    dim: Incomplete = ...,
    n: Incomplete = ...,
    prefix: Incomplete = ...,
    **kwargs: Incomplete,
) -> None: ...
def irfft(
    da: Incomplete,
    dim: Incomplete = ...,
    n: Incomplete = ...,
    prefix: Incomplete = ...,
    **kwargs: Incomplete,
) -> None: ...
def autocov(da: Incomplete, dim: Incomplete = ..., **kwargs: Incomplete) -> Incomplete: ...
def autocorr(da: Incomplete, dim: Incomplete = ..., **kwargs: Incomplete) -> None: ...
def geyer(acov: Incomplete, chain_mean_term: Incomplete, tau_hat: Incomplete) -> None: ...
def _ess(da: Incomplete, relative: Incomplete = ..., **kwargs: Incomplete) -> None: ...
def _ess_mean(da: Incomplete, relative: Incomplete = ..., **kwargs: Incomplete) -> None: ...
def _ess_bulk(da: Incomplete, relative: Incomplete = ..., **kwargs: Incomplete) -> None: ...
def ess(
    ds: Incomplete, group: Incomplete = ..., method: Incomplete = ..., **kwargs: Incomplete
) -> None: ...
