# File generated with docstub

import warnings
from collections.abc import Sequence

import numpy as np
from numpy.typing import ArrayLike, NDArray
from scipy import stats
from scipy.special import logsumexp

from arviz_stats.base.circular_utils import (
    circular_diff,
    circular_mean,
    circular_sd,
    circular_var,
)
from arviz_stats.base.core import _CoreBase
from arviz_stats.base.stats_utils import not_valid as _not_valid

class _DiagnosticsBase(_CoreBase):
    def _backtransform_ranks(self, arr: np.ndarray, c: float = ...) -> np.ndarray: ...
    def _z_scale(self, ary: np.ndarray) -> np.ndarray: ...
    def _split_chains(self, ary: ArrayLike) -> None: ...
    def _z_fold(self, ary: ArrayLike) -> None: ...
    def _rhat(self, ary: ArrayLike) -> None: ...
    def _rhat_rank(self, ary: ArrayLike) -> None: ...
    def _rhat_folded(self, ary: ArrayLike) -> None: ...
    def _rhat_z_scale(self, ary: ArrayLike) -> None: ...
    def _rhat_split(self, ary: ArrayLike) -> None: ...
    def _rhat_identity(self, ary: ArrayLike) -> None: ...
    def _ess(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_bulk(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_tail(self, ary: ArrayLike, prob: float, relative: bool = ...) -> None: ...
    def _ess_mean(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_sd(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_quantile(self, ary: ArrayLike, prob: float, relative: bool = ...) -> None: ...
    def _ess_local(self, ary: ArrayLike, prob: float, relative: bool = ...) -> None: ...
    def _ess_z_scale(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_folded(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_median(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_mad(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _ess_identity(self, ary: ArrayLike, relative: bool = ...) -> None: ...
    def _mcse_mean(self, ary: ArrayLike, circular: bool = ...) -> None: ...
    def _mcse_sd(self, ary: ArrayLike) -> None: ...
    def _mcse_median(self, ary: ArrayLike, circular: bool = ...) -> None: ...
    def _mcse_quantile(self, ary: ArrayLike, prob: float, circular: bool = ...) -> None: ...
    def _pareto_min_ss(self, ary: ArrayLike) -> None: ...
    def _psislw(self, ary: ArrayLike, r_eff: float) -> None: ...
    def _bfmi(self, ary: ArrayLike) -> None: ...
    def _loo(
        self,
        ary: np.ndarray,
        r_eff: float = ...,
        log_weights: np.ndarray | None = ...,
        pareto_k: float | None = ...,
        log_jacobian: float | None = ...,
    ) -> tuple[float, float, float]: ...
    def _loo_approximate_posterior(
        self,
        ary: np.ndarray,
        log_p: np.ndarray,
        log_q: np.ndarray,
        log_jacobian: float | None = ...,
    ) -> tuple[float, float, float]: ...
    @staticmethod
    def _loo_score(ary: np.ndarray, y_obs: float, log_weights: np.ndarray, kind: str) -> float: ...
    def _loo_pit(
        self,
        ary: np.ndarray,
        y_obs: float,
        log_weights: np.ndarray,
        rng: np.random.Generator | None = ...,
        pareto_pit: bool = ...,
    ) -> None: ...
    def _loo_expectation(self, ary: np.ndarray, log_weights: np.ndarray, kind: str) -> float: ...
    def _loo_quantile(self, ary: np.ndarray, log_weights: np.ndarray, prob: float) -> float: ...
    @staticmethod
    def _loo_r2(
        y_obs: np.ndarray,
        ypred_loo: np.ndarray,
        n_simulations: int = ...,
        circular: bool = ...,
        random_state: int = ...,
    ) -> np.ndarray: ...
    @staticmethod
    def _mixture(
        ary: np.ndarray,
        obs_axes: tuple[int],
        sample_axes: tuple[int],
        log_jacobian: np.ndarray | None = ...,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
    @staticmethod
    def _srs_estimator(y_sample: ArrayLike, n_data_points: int) -> tuple[float, float, float]: ...
    @staticmethod
    def _diff_srs_estimator(
        elpd_loo_i_sample: ArrayLike,
        lpd_approx_sample: ArrayLike,
        lpd_approx_all: ArrayLike,
        n_data_points: int,
    ) -> tuple[float, float, float]: ...
    @staticmethod
    def _weighted_quantile(ary: np.ndarray, weights: np.ndarray, prob: float) -> float: ...
    @staticmethod
    def _summary(elpd_i: np.ndarray, p_loo_i: np.ndarray) -> tuple[float, float, float, float]: ...
    def _pareto_pit_vec(
        self,
        draws_matrix: ArrayLike,
        y_obs_array: ArrayLike,
        log_weights: ArrayLike | None = ...,
        rng: np.random.Generator | None = ...,
    ) -> float: ...
    def _pareto_pit_single(
        self,
        draws: ArrayLike,
        y_val: float,
        lw: ArrayLike,
        rng: np.random.Generator,
        gpd_ok: bool,
        tail_ids: ArrayLike,
        ndraws_tail: int,
    ) -> None: ...
    def _pareto_khat(
        self,
        ary: ArrayLike,
        r_eff: float | None = ...,
        tail: str = ...,
        log_weights: bool = ...,
    ) -> float: ...
    @staticmethod
    def _get_ps_tails(n_draws: int, r_eff: float, tail: str) -> None: ...
    def _ps_tail(
        self,
        ary: NDArray,
        n_draws: int,
        n_draws_tail: int,
        smooth_draws: bool = ...,
        tail: str = ...,
        log_weights: bool = ...,
    ) -> tuple[NDArray, float]: ...
    @staticmethod
    def _gpdfit(ary: NDArray, weights: NDArray | None = ...) -> tuple[float, float]: ...
    @staticmethod
    def _gpinv(probs: ArrayLike, kappa: float, sigma: float, mu: float) -> None: ...
    @staticmethod
    def pgeneralized_pareto(
        q: ArrayLike,
        mu: float = ...,
        sigma: float = ...,
        k: float = ...,
        lower_tail: bool = ...,
        log_p: bool = ...,
    ) -> None: ...
    def _power_scale_sense(
        self,
        ary: ArrayLike,
        lower_w: ArrayLike,
        upper_w: ArrayLike,
        lower_alpha: float,
        upper_alpha: float,
    ) -> None: ...
    def _power_scale_lw(self, ary: ArrayLike, alpha: float) -> None: ...
    @staticmethod
    def _cjs_dist(ary: ArrayLike, weights: ArrayLike) -> None: ...
    def _rhat_nested_rank(self, ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    def _rhat_nested_folded(self, ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    def _rhat_nested_z_scale(self, ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    def _rhat_nested_split(self, ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    def _rhat_nested_identity(self, ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    @staticmethod
    def _rhat_nested(ary: ArrayLike, superchain_ids: ArrayLike) -> None: ...
    @staticmethod
    def _bayesian_r2(
        mu_pred: ArrayLike, scale: ArrayLike, scale_kind: str, circular: bool
    ) -> ArrayLike: ...
    @staticmethod
    def _residual_r2(y_obs: ArrayLike, mu_pred: ArrayLike, circular: bool) -> ArrayLike: ...
    @staticmethod
    def _mae(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _mse(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _rmse(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _acc(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _acc_balanced(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
