# File generated with docstub

import numpy as np
from _typeshed import Incomplete
from numpy.typing import ArrayLike, NDArray

from arviz_stats.base.core import _CoreBase

class _DiagnosticsBase(_CoreBase):
    def _backtransform_ranks(self, arr: np.ndarray, c: float = ...) -> np.ndarray: ...
    def _z_scale(self, ary: np.ndarray) -> np.ndarray: ...
    def _split_chains(self, ary: Incomplete) -> None: ...
    def _z_fold(self, ary: Incomplete) -> None: ...
    def _rhat(self, ary: Incomplete) -> None: ...
    def _rhat_rank(self, ary: Incomplete) -> None: ...
    def _rhat_folded(self, ary: Incomplete) -> None: ...
    def _rhat_z_scale(self, ary: Incomplete) -> None: ...
    def _rhat_split(self, ary: Incomplete) -> None: ...
    def _rhat_identity(self, ary: Incomplete) -> None: ...
    def _ess(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_bulk(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_tail(self, ary: Incomplete, prob: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_mean(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_sd(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_quantile(
        self, ary: Incomplete, prob: Incomplete, relative: Incomplete = ...
    ) -> None: ...
    def _ess_local(self, ary: Incomplete, prob: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_z_scale(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_folded(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_median(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_mad(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _ess_identity(self, ary: Incomplete, relative: Incomplete = ...) -> None: ...
    def _mcse_mean(self, ary: Incomplete, circular: Incomplete = ...) -> None: ...
    def _mcse_sd(self, ary: Incomplete) -> None: ...
    def _mcse_median(self, ary: Incomplete, circular: Incomplete = ...) -> None: ...
    def _mcse_quantile(
        self, ary: Incomplete, prob: Incomplete, circular: Incomplete = ...
    ) -> None: ...
    def _pareto_min_ss(self, ary: Incomplete) -> None: ...
    def _psislw(self, ary: Incomplete, r_eff: Incomplete) -> None: ...
    def _bfmi(self, ary: Incomplete) -> None: ...
    def _loo(
        self,
        ary: np.ndarray,
        r_eff: float = ...,
        log_weights: np.ndarray | None = ...,
        pareto_k: float | None = ...,
        log_jacobian: float | None = ...,
    ) -> tuple[float, float, float]: ...
    def _loo_approximate_posterior(
        self,
        ary: np.ndarray,
        log_p: np.ndarray,
        log_q: np.ndarray,
        log_jacobian: float | None = ...,
    ) -> tuple[float, float, float]: ...
    @staticmethod
    def _loo_score(ary: np.ndarray, y_obs: float, log_weights: np.ndarray, kind: str) -> float: ...
    def _loo_pit(
        self,
        ary: np.ndarray,
        y_obs: float,
        log_weights: np.ndarray,
        rng: np.random.Generator | None = ...,
        pareto_pit: bool = ...,
    ) -> None: ...
    def _loo_expectation(self, ary: np.ndarray, log_weights: np.ndarray, kind: str) -> float: ...
    def _loo_quantile(self, ary: np.ndarray, log_weights: np.ndarray, prob: float) -> float: ...
    @staticmethod
    def _loo_r2(
        y_obs: np.ndarray,
        ypred_loo: np.ndarray,
        n_simulations: int = ...,
        circular: bool = ...,
        random_state: int = ...,
    ) -> np.ndarray: ...
    @staticmethod
    def _mixture(
        ary: np.ndarray,
        obs_axes: tuple[int],
        sample_axes: tuple[int],
        log_jacobian: np.ndarray | None = ...,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
    @staticmethod
    def _srs_estimator(y_sample: ArrayLike, n_data_points: int) -> tuple[float, float, float]: ...
    @staticmethod
    def _diff_srs_estimator(
        elpd_loo_i_sample: ArrayLike,
        lpd_approx_sample: ArrayLike,
        lpd_approx_all: ArrayLike,
        n_data_points: int,
    ) -> tuple[float, float, float]: ...
    @staticmethod
    def _weighted_quantile(ary: np.ndarray, weights: np.ndarray, prob: float) -> float: ...
    @staticmethod
    def _summary(elpd_i: np.ndarray, p_loo_i: np.ndarray) -> tuple[float, float, float, float]: ...
    def _pareto_pit_vec(
        self,
        draws_matrix: ArrayLike,
        y_obs_array: ArrayLike,
        log_weights: ArrayLike | None = ...,
        rng: np.random.Generator | None = ...,
    ) -> float: ...
    def _pareto_pit_single(
        self,
        draws: Incomplete,
        y_val: Incomplete,
        lw: Incomplete,
        rng: Incomplete,
        gpd_ok: Incomplete,
        tail_ids: Incomplete,
        ndraws_tail: Incomplete,
    ) -> None: ...
    def _pareto_khat(
        self,
        ary: ArrayLike,
        r_eff: float | None = ...,
        tail: str = ...,
        log_weights: bool = ...,
    ) -> float: ...
    @staticmethod
    def _get_ps_tails(n_draws: Incomplete, r_eff: Incomplete, tail: Incomplete) -> None: ...
    def _ps_tail(
        self,
        ary: Incomplete,
        n_draws: int,
        n_draws_tail: int,
        smooth_draws: bool = ...,
        tail: str = ...,
        log_weights: bool = ...,
    ) -> tuple[NDArray, float]: ...
    @staticmethod
    def _gpdfit(ary: NDArray, weights: NDArray | None = ...) -> tuple[float, float]: ...
    @staticmethod
    def _gpinv(probs: Incomplete, kappa: Incomplete, sigma: Incomplete, mu: Incomplete) -> None: ...
    @staticmethod
    def pgeneralized_pareto(
        q: ArrayLike,
        mu: float = ...,
        sigma: float = ...,
        k: float = ...,
        lower_tail: bool = ...,
        log_p: bool = ...,
    ) -> None: ...
    def _power_scale_sense(
        self,
        ary: Incomplete,
        lower_w: Incomplete,
        upper_w: Incomplete,
        lower_alpha: Incomplete,
        upper_alpha: Incomplete,
    ) -> None: ...
    def _power_scale_lw(self, ary: Incomplete, alpha: Incomplete) -> None: ...
    @staticmethod
    def _cjs_dist(ary: Incomplete, weights: Incomplete) -> None: ...
    def _rhat_nested_rank(self, ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    def _rhat_nested_folded(self, ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    def _rhat_nested_z_scale(self, ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    def _rhat_nested_split(self, ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    def _rhat_nested_identity(self, ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    @staticmethod
    def _rhat_nested(ary: Incomplete, superchain_ids: Incomplete) -> None: ...
    @staticmethod
    def _bayesian_r2(
        mu_pred: ArrayLike, scale: Incomplete, scale_kind: str, circular: bool
    ) -> ArrayLike: ...
    @staticmethod
    def _residual_r2(y_obs: ArrayLike, mu_pred: ArrayLike, circular: bool) -> ArrayLike: ...
    @staticmethod
    def _mae(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _mse(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _rmse(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _acc(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
    @staticmethod
    def _acc_balanced(observed: ArrayLike, predicted: ArrayLike) -> tuple[float, float]: ...
