# File generated with docstub

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from _typeshed import Incomplete
from xarray import DataArray

__all__ = ["ELPDData", "get_function", "get_log_likelihood"]

def get_function(func_name: str) -> Callable: ...
def get_array_function(func_name: str) -> Callable: ...
def get_log_likelihood(idata: Incomplete, var_name: Incomplete = ...) -> None: ...
def get_log_likelihood_dataset(idata: Incomplete, var_names: Incomplete = ...) -> None: ...
def get_log_likelihood_dataarray(data: Incomplete, var_name: Incomplete = ...) -> None: ...
def get_log_prior(idata: Incomplete, var_names: Incomplete = ...) -> None: ...

BASE_FMT: Incomplete
POINTWISE_LOO_FMT: Incomplete
SCALE_DICT: Incomplete

@dataclass
class ELPDData:
    kind: str
    elpd: float
    se: float
    p: float
    n_samples: int
    n_data_points: int
    scale: str
    warning: bool
    good_k: float
    elpd_i: DataArray = ...
    pareto_k: DataArray = ...
    approx_posterior: bool = ...
    subsampling_se: float = ...
    subsample_size: int = ...
    log_p: object = ...
    log_q: object = ...
    thin_factor: object = ...
    log_weights: DataArray = ...
    n_folds: int = ...
    loo_subsample_observations: np.ndarray = ...
    elpd_loo_approx: DataArray = ...
    log_jacobian: DataArray = ...
    influence_pareto_k: DataArray = ...
    n_eff_i: DataArray = ...

    def __str__(self) -> None: ...
    def __repr__(self) -> None: ...
    def __getitem__(self, key: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, item: Incomplete) -> None: ...

def _warn_non_unique_coords(xr_obj: Incomplete, dims_to_reduce: Incomplete) -> None: ...
def _apply_multi_input_function(
    name: Incomplete,
    data: Incomplete,
    dims: Incomplete,
    dims_arg: Incomplete,
    *,
    group: Incomplete,
    var_names: Incomplete,
    filter_vars: Incomplete,
    coords: Incomplete,
    **kwargs: Incomplete,
) -> None: ...
