# File generated with docstub

from _typeshed import Incomplete

def validate_dims(dims: str) -> list: ...
def validate_dims_chain_draw_axis(dims: Incomplete) -> list: ...
def validate_ci_prob(prob: Incomplete) -> float: ...
def validate_prob(prob: Incomplete, allow_0: Incomplete = ...) -> None: ...
